name: VPS Hunter Simple

on:
  workflow_dispatch:

jobs:
  hunter:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot8857993443:AAFeHfRq_9qjcPCXWldiFDwNCMvlH_Khq24/sendMessage" -d "chat_id=7576216084&text=✅ Test from GitHub Actions!"
